use_frameworks!

platform :ios, '12.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'Appointments_Example' do
  pod 'Appointments', :path => '../'

  target 'Appointments_Tests' do
    inherit! :search_paths

    
  end
end
